LabCommunalServices/Controllers/HomeController.cs
using LabCommunalServices.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LabCommunalServices.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LabCommunalServices/Controllers/PaymentDocumentController.cs
using Business.Interop;
using Business.Services;
using LabCommunalServices.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LabCommunalServices.Controllers
{
    public class PaymentDocumentController : Controller
    {
        private readonly IPaymentDocService _payDocService;
        private readonly IClientService _clientService;
        private readonly IContractService _contractService;

        public PaymentDocumentController(IPaymentDocService payDocService, IClientService clientService, IContractService contractService)
        {
            _payDocService = payDocService;
            _clientService = clientService;
            _contractService = contractService;
        }

        public IActionResult Index()
        {
            var payDocs = _payDocService.GetAll();
            return View(payDocs);
        }
        public IActionResult Home(int id)
        {
            var payDoc = _payDocService.GetById(id);
            return View(payDoc);
        }
        public IActionResult Edit(int? id)
        {
            ViewBag.Clients = _clientService.GetAll()
                .OrderBy(a => a.ToString());
            ViewBag.Contracts = _contractService.GetAll()
                .OrderBy(a => a.ToString());
            if (id == null)
                return View();
            var payDoc = _payDocService.GetById(id.Value);
            return View(payDoc);
        }

        [HttpPost]
        public IActionResult Edit(PaymentDocDto paymentDoc)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Edit), new { id = paymentDoc.Id });
            var res = _payDocService.CreateOrUpdate(paymentDoc);
            return RedirectToAction(nameof(Home), new { id = res.Id });
        }
        public IActionResult Delete(int id)
        {
            _payDocService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LabCommunalServices/Views/PaymentDocument/Edit.cshtml
@model Business.Interop.PaymentDocDto

@{ ViewData["Title"] = "Добавление"; }

<!DOCTYPE html>

<html>
<body>
    <h4>Создание платёжного документа</h4>
    <form asp-controller="PaymentDocument" asp-action="Edit" method="post">
        @if (Model != null)
        {
    <input type="hidden" name="Id" value="@Model.Id"></input>}
        <table class="table">
            <tr>
                <td>Наименование документа:</td>
                <td><input type="text" required name="Name" value="@Model?.Name" /></td>
            </tr>
            <tr>
                <td>Клиент:</td>
                <td>
                    <select name="ClientID" required>
                        @foreach (var client in ViewBag.Clients)
                        {
                            if (Model?.Client?.Id == client.Id)
                            {
                                <option value="@client.Id" selected>@client.FIO</option>
                            }
                            else
                            {
                                <option value="@client.Id">@client.FIO</option>
                            }
                        }
                    </select>
                </td>
                <td>Контракт:</td>
                <td>
                    <select name="ContractId" required>
                        @foreach (var contract in ViewBag.Contracts)
                        {
                            if (Model?.Contract?.Id == contract.Id)
                            {
                                <option value="@contract.Id" selected>@contract.ContractNumber</option>
                            }
                            else
                            {
                                <option value="@contract.Id">@contract.ContractNumber</option>
                            }
                        }
                    </select>
                </td>
            </tr>
        </table>
        <input type="submit" value="Отправить" />
        <p></p>
        <h4><a asp-controller="PaymentDocument" asp-action="Index">Назад</a></h4>
        <hr />
    </form>
</body>
</html>

LabCommunalServices/Views/PaymentDocument/Home.cshtml
@using Business.Interop;
@model PaymentDocDto

@{ ViewData["Title"] = "Информация о платёжном документе"; }

<!DOCTYPE html>

<html>
<body>
    @{

    <table class="table">
        <tr>
            <th>Название документа</th>
            <th>Клиент</th>
            <th>Номер контракта</th>
        </tr>
        <tr>
            <td>@Model.Name</td>
            <td>@Model.Client?.FIO</td>
            <td>@Model.Contract?.ContractNumber</td>
        </tr>
    </table>
    <h5><a asp-controller="PaymentDocument" asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a></h5>
    <hr />
    <h5><a asp-controller="PaymentDocument" asp-action="Delete" asp-route-id="@Model.Id">Удалить</a></h5>
    <hr />
    <h5><a asp-controller="PaymentDocument" asp-action="Index" asp-route-id="@Model.Id">Вернуться к списку платёжных документов</a></h5>
    <hr />
    }
</body>
</html>

LabCommunalServices/Views/PaymentDocument/Index.cshtml
@model IEnumerable<Business.Interop.PaymentDocDto>

@{ ViewData["Title"] = "Платёжные документы"; }

<!DOCTYPE html>

<html>
<body>
    @if (!Model.Any())
    {
        <p>Документов еще не добавлено</p>
    }
    else
    {
    <table class="table">
    <tr>
        <th>Наименование документа</th>
        <th>ФИО клиента</th>
        <th>Номер контракта</th>
        <th></th>
    </tr>
    @foreach (var payDoc in Model)
    {
    <tr>
        <td>@payDoc.Name</td>
        <td>@payDoc.Client?.FIO</td>
        <td>@payDoc.Contract?.ContractNumber</td>
        <td><a asp-controller="PaymentDocument" asp-action="Home" asp-route-id="@payDoc.Id"><h6>Подробности</h6></a></td>
    </tr>
    }
    </table>
    <br />
    }
    <h4><a asp-controller="PaymentDocument" asp-action="Edit">Создать</a></h4>
    <hr />
    <h4><a asp-controller="Home" asp-action="Index">Назад</a></h4>
    <hr />
</body>
</html>