LabCommunalServices/Controllers/ContractController.cs
using Business.Interop;
using Business.Services;
using LabCommunalServices.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LabCommunalServices.Controllers
{
    public class ContractController : Controller
    {
        private readonly IContractService _contractService;
        private readonly ILawService _lawService;
        private readonly IClientService _clientService;
        private readonly IServiceService _serviceService;


        public ContractController(IContractService contractService, IServiceService serviceService, ILawService lawService, IClientService clientService)
        {
            _contractService = contractService;
            _lawService = lawService;
            _clientService = clientService;
            _serviceService = serviceService;
        }

        public IActionResult Index()
        {
            var contracts = _contractService.GetAll();
            return View(contracts);
        }
        public IActionResult Home(int id)
        {
            var contract = _contractService.GetById(id);
            return View(contract);
        }
        public IActionResult Edit(int? id)
        {
            ViewBag.Laws = _lawService.GetAll()
                .OrderBy(a => a.ToString());
            ViewBag.Clients = _clientService.GetAll()
                .OrderBy(a => a.ToString());
            ViewBag.Services = _serviceService.GetAll()
                .OrderBy(a => a.ToString());
            if (id == null)
                return View();
            var contract = _contractService.GetById(id.Value);
            return View(contract);
        }

        [HttpPost]
        public IActionResult Edit(ContractDto contract)
        {
            if (!ModelState.IsValid)
                return RedirectToAction(nameof(Edit), new { id = contract.Id });

            var res = _contractService.CreateOrUpdate(contract);
            return RedirectToAction(nameof(Home), new { id = res.Id });
        }
        public IActionResult Delete(int id)
        {
            _contractService.Delete(id);
            return RedirectToAction(nameof(Index));
        }
    }
}

LabCommunalServices/Controllers/HomeController.cs
using LabCommunalServices.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace LabCommunalServices.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LabCommunalServices/Views/Contract/Edit.cshtml
@model Business.Interop.ContractDto

@{ ViewData["Title"] = "Изменение"; }

<!DOCTYPE html>

<html>
<body>
    <h4>Создание контракта</h4>
    <form asp-controller="Contract" asp-action="Edit" method="post">
    @if (Model != null)
    {
        <input type="hidden" name="Id" value="@Model.Id"></input>
    }
    <table class="table">
        <tr>
            <td>Номер контракта:</td>
            <td><input type="text" pattern="\d*" required name="ContractNumber" value="@Model?.ContractNumber" /></td>
        </tr>
        <tr>
            <td>Сумма выплаты:</td>
            <td><input type="text" pattern="\d*" placeholder="10000" required name="PayableAmount" value="@Model?.PayableAmount" /></td>
        </tr>
        <tr>
            <td>Дата выплаты:</td>
            <td><input type="text" pattern="[0-9]{2}.[0-9]{2}.[0-9]{4}*" placeholder="25.01.2022" required name="PaymentTerm" value="@Model?.PaymentTerm" /></td>
        </tr>
        <tr>
            <td>Клиент:</td>
            <td>
                <select name="ClientID" required>
                    @foreach (var client in ViewBag.Clients)
                    {
                        if (Model?.Client?.Id == client.Id)
                        {
                            <option value="@client.Id" selected>@client.FIO</option>

                        }
                        else
                        {
                            <option value="@client.Id">@client.FIO</option>
                        }
                    }
                </select>
            </td>
            <td>Услуга:</td>
            <td>
                <select name="ServiceId" required>
                    @foreach (var service in ViewBag.Services)
                    {
                        if (Model?.Service?.Id == service.Id)
                        {
                            <option value="@service.Id" selected>@service.Name</option>
                        }
                        else
                        {
                            <option value="@service.Id">@service.Name</option>
                        }
                    }
                </select>
            </td>
            <td>Закон:</td>
            <td>
                <select name="LawId" required>
                    @foreach (var law in ViewBag.Laws)
                    {
                        if (Model?.Law?.Id == law.Id)
                        {
        <option value="@law.Id" selected>@law.Wording</option> }
                        else
                        {
        <option value="@law.Id">@law.Wording</option>}
                    }
                </select>
            </td>
        </tr>
    </table>
        <input type="submit" value="Отправить" />
        <p></p>
        <hr />
        <h4><a asp-controller="Contract" asp-action="Index">Назад</a></h4>
        <hr />
    </form>
</body>
</html>

LabCommunalServices/Views/Contract/Home.cshtml
@using Business.Interop;
@model ContractDto

@{ ViewData["Title"] = "Информация о контракте"; }

<!DOCTYPE html>

<html>
<body>
    @{

    <table class="table">
        <tr>
            <th>Номер контракта</th>
            <th>Сумма выплаты</th>
            <th>Дата выплаты</th>
            <th>Предоставляемая услуга</th>
            <th>Клиент</th>
            <th>Закон</th>
        </tr>
        <tr>
            <td>@Model.ContractNumber</td>
            <td>@Model.PayableAmount</td>
            <td>@Model.PaymentTerm</td>
            <td>@Model.Service?.Name</td>
            <td>@Model.Client?.FIO</td>
            <td>@Model.Law?.Wording</td>
        </tr>
    </table>
    <h5><a asp-controller="Contract" asp-action="Edit" asp-route-id="@Model.Id">Редактировать</a></h5>
    <hr />
    <h5><a asp-controller="Contract" asp-action="Delete" asp-route-id="@Model.Id">Удалить</a></h5>
    <hr />
    <h5><a asp-controller="Contract" asp-action="Index" asp-route-id="@Model.Id">Вернуться к списку контрактов</a></h5>
    <hr />}
</body>
</html>

LabCommunalServices/Views/Contract/Index.cshtml
@model IEnumerable<Business.Interop.ContractDto>

@{ ViewData["Title"] = "Контракты"; }

<!DOCTYPE html>

<html>
<body>
    @if (!Model.Any())
    {
        <p>Контрактов еще не добавлено</p> }
    else
    {
    <table class="table">
        <tr>
            <th>Номер контракта</th>
            <th>Сумма выплаты</th>
            <th>Клиент</th>
            <th></th>
        </tr>
        @foreach (var contract in Model)
        {
        <tr>
            <td>@contract.ContractNumber</td>
            <td>@contract.PayableAmount</td>
            <td>@contract.Client?.FIO</td>
            <td><a asp-controller="Contract" asp-action="Home" asp-route-id="@contract.Id"><h6>Подробности</h6></a></td>
        </tr>
    }
    </table>
    <br />
    }
    <h4><a asp-controller="Contract" asp-action="Edit">Создать</a></h4>
    <hr />
    <h4><a asp-controller="Home" asp-action="Index">Назад</a></h4>
    <hr />
</body>
</html>